language: cpp
compiler: gcc
dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - cmake

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make