language: cpp
compiler: gcc
dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - cmake
      - cppcheck

before_script:
  - gcc -v && g++ -v && cmake --version
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
  - cppcheck --quiet --error-exitcode=1 .
  - ls .